In [2]:
import numpy as np

## How to create an boolen array

In [5]:
np.ones((3,3), dtype= bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## How to extract items that satisfy a given condition from 1D array?

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

## How to replace items that satisfy a condition with another value in numpy array?

### replacing all odd number with -1

In [9]:
arr[arr%2 ==1] = -1

In [10]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## How to replace items that satisfy a condition without affecting the original array?

### Replace all odd numbers in arr with -1 without changing arr

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
out = np.where(arr%2==1, -1, arr)

In [18]:
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


## How to reshape an array?

### Convert a 1D array to a 2D array with 2 rows

In [22]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## How to stack two arrays vertically?

In [25]:
a = np.arange(10).reshape(2,-1)
b = np.ones(10).reshape(2,-1)

In [38]:
np.vstack([a,b])

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.concatenate([a,b],axis=0)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## How to stack two arrays horizontally?

In [43]:
a = np.arange(10).reshape(2,-1)
b = np.ones(10).reshape(2,-1)

In [44]:
np.hstack([a,b])

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

In [45]:
np.concatenate([a,b], axis=1)

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## How to generate custom sequence in numpy without hardcoding?

In [53]:
a = np.r_[1,2,3]

In [55]:
np.r_[np.repeat(a, 3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## How to get two common items between two python numpy arrays?

In [64]:
a = np.array([i for i in range(10)])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [69]:
np.intersect1d(a,b)

array([2, 4, 7, 8, 9])

## How to remove from one array those items that exist in another?

In [72]:
a = np.array([i for i in range(10)])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [75]:
np.setdiff1d(a,b)

array([0, 1, 3, 5, 6])

## How to get the positions where elements of two arrays match?

In [81]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [82]:
np.where(a==b)

(array([1, 3, 5, 7]),)

## How to extract all numbers between a given range from a numpy array?

### Extract all number between 5 and 10

In [83]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [88]:
np.where(a<15)

(array([0, 1, 2, 3, 4, 5]),)