In [2]:
import numpy as np

## How to create an boolen array

In [5]:
np.ones((3,3), dtype= bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## How to extract items that satisfy a given condition from 1D array?

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

## How to replace items that satisfy a condition with another value in numpy array?

### replacing all odd number with -1

In [9]:
arr[arr%2 ==1] = -1

In [10]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## How to replace items that satisfy a condition without affecting the original array?

### Replace all odd numbers in arr with -1 without changing arr

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
out = np.where(arr%2==1, -1, arr)

In [18]:
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


## How to reshape an array?

### Convert a 1D array to a 2D array with 2 rows

In [22]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## How to stack two arrays vertically?

In [25]:
a = np.arange(10).reshape(2,-1)
b = np.ones(10).reshape(2,-1)

In [38]:
np.vstack([a,b])

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.concatenate([a,b],axis=0)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## How to stack two arrays horizontally?

In [43]:
a = np.arange(10).reshape(2,-1)
b = np.ones(10).reshape(2,-1)

In [44]:
np.hstack([a,b])

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

In [45]:
np.concatenate([a,b], axis=1)

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## How to generate custom sequence in numpy without hardcoding?

In [53]:
a = np.r_[1,2,3]

In [55]:
np.r_[np.repeat(a, 3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## How to get two common items between two python numpy arrays?

In [64]:
a = np.array([i for i in range(10)])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [69]:
np.intersect1d(a,b)

array([2, 4, 7, 8, 9])

## How to remove from one array those items that exist in another?

In [72]:
a = np.array([i for i in range(10)])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [75]:
np.setdiff1d(a,b)

array([0, 1, 3, 5, 6])

## How to get the positions where elements of two arrays match?

In [81]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [82]:
np.where(a==b)

(array([1, 3, 5, 7]),)

## How to extract all numbers between a given range from a numpy array?

### Extract all number between 5 and 10

In [90]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [97]:
index = np.where((a>5)&(a<15))
index

(array([1, 3, 4]),)

In [95]:
a[index]

array([ 6,  9, 10])

## How to make a python function that handles scalars to work on numpy arrays?

### Convert the function maxx that works on two scalars, to work on two arrays.

In [104]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

5

In [105]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])

In [107]:
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [131]:
def maxx2(x,y):
    out = []
    for i in range(len(x)):
        if x[i]>=y[i]:
            out.append(x[i]/1.)
        else:
            out.append(y[i]/1.)
    return out

In [132]:
maxx2(a,b)

[6.0, 7.0, 9.0, 8.0, 9.0, 7.0, 5.0]

## How to swap two columns in a 2D array?

In [161]:
arr = np.hstack([np.arange(9).reshape(3,3),np.tile([1,2,3],reps=3).reshape(3,3)])

In [162]:
arr

array([[0, 1, 2, 1, 2, 3],
       [3, 4, 5, 1, 2, 3],
       [6, 7, 8, 1, 2, 3]])

In [164]:
arr[:, [4,0,3,2,5,1]]

array([[2, 0, 1, 2, 3, 1],
       [2, 3, 1, 5, 3, 4],
       [2, 6, 1, 8, 3, 7]])

## How to swap two rows in a 2D array?

In [165]:
arr = np.vstack([np.arange(9).reshape(3,3),np.tile([1,2,3],reps=3).reshape(3,3)])

In [166]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [168]:
arr[[4,1,3,2,0,5],:]

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [6, 7, 8],
       [0, 1, 2],
       [1, 2, 3]])

## How to reverse the rows of a 2D array?

In [171]:
arr = np.arange(16).reshape(4,4)

In [188]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [189]:
arr[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

## How to reverse the columns of a 2D array?

In [190]:
arr = np.arange(16).reshape(4,4)

In [191]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [194]:
arr[:,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

## How to create a 2D array containing random floats between 5 and 10?

In [204]:
np.random.randint(low=5,high=10,size=(5,3))

array([[8, 5, 7],
       [9, 5, 6],
       [9, 6, 7],
       [8, 5, 5],
       [7, 5, 5]])

## How to print only 3 decimal places in python numpy array?

In [235]:
arr = np.random.random(size=(5,3))

In [236]:
arr

array([[0.37121821882422557 , 0.8554778163858168  , 0.017409268134228828],
       [0.9910112640980057  , 0.43440362204458616 , 0.7143579249663314  ],
       [0.370795258769402   , 0.8828554430231962  , 0.2440804589816331  ],
       [0.22145574248714295 , 0.20140327572941774 , 0.5845808110226164  ],
       [0.9817955198148519  , 0.794564305290951   , 0.7298968590444426  ]])

In [243]:
np.set_printoptions(precision=3)
arr[:3]

array([[0.371, 0.855, 0.017],
       [0.991, 0.434, 0.714],
       [0.371, 0.883, 0.244]])

## How to pretty print a numpy array by supressing the scientific notation (like 1e10)?

### Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [244]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [249]:
np.set_printoptions(suppress=True, precision=6)

In [250]:
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

## How to limit the number of items printed in output of numpy array?

In [251]:
a =np.arange(15)

In [252]:
np.set_printoptions(threshold=6)

In [253]:
a

array([ 0,  1,  2, ..., 12, 13, 14])

## How to print the full numpy array without truncating

In [254]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [264]:
np.set_printoptions(threshold=len(a))

In [265]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])